eb_api:
    resource: "@EBApiBundle/Controller/"
    type:     annotation
    prefix:   /api

eb_core:
    resource: "@EBCoreBundle/Controller/"
    type:     annotation
    prefix:   /

eb_user:
    resource: "@EBUserBundle/Controller/"
    type:     annotation
    prefix:   /

# FOSUserBundle routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
