eb_api:
    resource: "@EBApiBundle/Controller/"
    type:     annotation
    prefix:   /

eb_core:
    resource: "@EBCoreBundle/Controller/"
    type:     annotation
    prefix:   /

eb_user:
    resource: "@EBUserBundle/Controller/"
    type:     annotation
    prefix:   /
